---
title: Der Eurolek Projekt
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: germanocaldeira@gmail.com
description: 'Um Volkswagen Golf Mk3 mexicano, com visual euro, customizado no Brasil
  ;-)

'
baseurl: "/eurolek"
url: https://germanocaldeira.github.io/eurolek
twitter_username: germanocaldeira
github_username: germanocaldeira
instagram_username: germanocaldeira
facebook_username: germanocaldeira
email_username: germanocaldeira
css_folder: asets/_stylesheets
js_folder: assets/_javascripts
img_folder: assets/images
font_folder: assets/_fonts
markdown: kramdown
excerpt_separator: "<!--more-->"
