# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Der Eurolek Projekt    
email: germanocaldeira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um Volkswagen Golf Mk3 mexicano, com visual euro, customizado no Brasil ;-)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://germanocaldeira.github.io/eurolek/" # the base hostname & protocol for your site
twitter_username: germanocaldeira
github_username:  germanocaldeira

# Build settings
markdown: kramdown

